// ------------------------------------------------------------
// BCI Waveform Replay - Digilent WaveForms / AD3
// ------------------------------------------------------------
// Loads a waveform CSV generated by Kenny's Python script,
// validates the import, checks for the WaveGen instrument,
// normalizes the biological waveform, and configures AD3 output.
//
// Expected CSV:
//   time,amplitude
//   ...
//
// IMPORTANT:
// Use forward slashes "/" in Windows file paths.
// ------------------------------------------------------------


// ------------------------------------------------------------
// USER CONFIGURATION
// ------------------------------------------------------------

var fileName =
    "C:/Users/mark/Desktop/BCI-CortexSignals/WaveGen/BCI_Capstone_Signals/positive_then_negative.csv";

// Waveform period from Kenny's Python script.
var period_ms = 5.0;

// Desired AD3 peak scaling voltage.
// Example:
// 1.2 V through a 10,000:1 attenuator = 120 uV
var ad3Amplitude_V = 1.2;

// Convert period to repetition frequency.
var frequency_Hz = 1000.0 / period_ms;


// ------------------------------------------------------------
// STARTUP
// ------------------------------------------------------------

print("");
print("========================================");
print("BCI Waveform Replay");
print("========================================");

print("");
print("Waveform file:");
print(fileName);

print("");
print("Configured period: " + period_ms + " ms");
print("Configured frequency: " + frequency_Hz + " Hz");
print("Configured AD3 amplitude: " + ad3Amplitude_V + " V");


// ------------------------------------------------------------
// 1. IMPORT CSV
// ------------------------------------------------------------

print("");
print("----------------------------------------");
print("STEP 1: Importing CSV");
print("----------------------------------------");

// true = skip first time column
var imported = FileImport(fileName, true);

if (imported === false) {

    print("");
    print("ERROR: CSV import failed.");
    print("");
    print("Check the following:");
    print("  1. Verify the file path is correct.");
    print("  2. Use forward slashes '/' in Windows paths.");
    print("  3. Make sure the CSV file exists.");
    print("  4. Confirm the CSV format is valid.");
    print("  5. Try a simple CSV to isolate format problems.");

    print("");
    print("Example valid Windows path:");
    print("C:/Users/name/Desktop/test.csv");
}


// ------------------------------------------------------------
// 2. CHECK WAVEGEN INSTRUMENT
// ------------------------------------------------------------

print("");
print("----------------------------------------");
print("STEP 2: Checking WaveGen");
print("----------------------------------------");

var wavegenAvailable = false;

if (typeof Wavegen1 === "undefined") {

    print("");
    print("ERROR: Wavegen1 was not found.");
    print("");
    print("Possible fixes:");
    print("  1. Open a WaveGen instrument in WaveForms.");
    print("  2. Return to the Script tool and run again.");
    print("  3. Check the instrument name.");
    print("  4. Instrument names are case-sensitive.");

    print("");
    print("Expected instrument name:");
    print("Wavegen1");

}
else {

    wavegenAvailable = true;

    print("");
    print("Wavegen1 found.");
}


// ------------------------------------------------------------
// 3. CONTINUE ONLY IF SETUP IS VALID
// ------------------------------------------------------------

if (imported === false || !wavegenAvailable) {

    print("");
    print("========================================");
    print("SETUP FAILED");
    print("========================================");
    print("");
    print("Resolve the errors above and run again.");

}
else {

    // --------------------------------------------------------
    // 4. EXTRACT WAVEFORM COLUMN
    // --------------------------------------------------------

    print("");
    print("----------------------------------------");
    print("STEP 3: Extracting waveform data");
    print("----------------------------------------");

    print("");
    print("Imported column count: " + imported.length);

    if (imported.length === 0) {

        print("");
        print("ERROR: No waveform columns were imported.");

    }
    else {

        // FileImport(..., true) skips the time column.
        // imported[0] is therefore the amplitude column.
        var rawWave = imported[0];

        print("Waveform sample count: " + rawWave.length);

        if (rawWave.length === 0) {

            print("");
            print("ERROR: Waveform contains zero samples.");

        }
        else {

            print("First sample: " + rawWave[0]);
            print("Last sample: " + rawWave[rawWave.length - 1]);


            // ------------------------------------------------
            // 5. ANALYZE WAVEFORM
            // ------------------------------------------------

            print("");
            print("----------------------------------------");
            print("STEP 4: Analyzing waveform");
            print("----------------------------------------");

            var minVal = rawWave[0];
            var maxVal = rawWave[0];

            for (var i = 1; i < rawWave.length; i++) {

                if (rawWave[i] < minVal) {
                    minVal = rawWave[i];
                }

                if (rawWave[i] > maxVal) {
                    maxVal = rawWave[i];
                }
            }

            var maxAbsolute =
                Math.max(Math.abs(minVal), Math.abs(maxVal));

            print("");
            print("Waveform minimum: " + minVal + " uV");
            print("Waveform maximum: " + maxVal + " uV");
            print("Maximum absolute amplitude: " + maxAbsolute + " uV");


            // ------------------------------------------------
            // 6. NORMALIZE WAVEFORM
            // ------------------------------------------------

            print("");
            print("----------------------------------------");
            print("STEP 5: Normalizing waveform");
            print("----------------------------------------");

            var wave = Array();

            for (var j = 0; j < rawWave.length; j++) {

                wave.push(rawWave[j] / maxAbsolute);

            }

            var normMin = wave[0];
            var normMax = wave[0];

            for (var k = 1; k < wave.length; k++) {

                if (wave[k] < normMin) {
                    normMin = wave[k];
                }

                if (wave[k] > normMax) {
                    normMax = wave[k];
                }
            }

            print("");
            print("Normalized minimum: " + normMin);
            print("Normalized maximum: " + normMax);

            if (normMin < -1.0 || normMax > 1.0) {

                print("");
                print("ERROR: Normalized waveform exceeds -1 to +1.");

            }
            else {

                print("");
                print("Normalization successful.");


                // --------------------------------------------
                // 7. CALCULATE EXPECTED SAMPLE RATE
                // --------------------------------------------

                var expectedSampleRate =
                    rawWave.length * frequency_Hz;

                print("");
                print("----------------------------------------");
                print("STEP 6: Waveform timing");
                print("----------------------------------------");

                print("");
                print("Samples: " + rawWave.length);
                print("Period: " + period_ms + " ms");
                print("Frequency: " + frequency_Hz + " Hz");
                print("Expected sample rate: " +
                      expectedSampleRate + " Hz");


                // --------------------------------------------
                // 8. LOAD CUSTOM WAVEFORM
                // --------------------------------------------

                print("");
                print("----------------------------------------");
                print("STEP 7: Loading custom waveform");
                print("----------------------------------------");

                Wavegen1.Custom.set("BCI_Waveform", wave);

                print("");
                print("Custom waveform loaded:");
                print("BCI_Waveform");


                // --------------------------------------------
                // 9. CONFIGURE WAVEGEN
                // --------------------------------------------

                print("");
                print("----------------------------------------");
                print("STEP 8: Configuring WaveGen");
                print("----------------------------------------");

                Wavegen1.Channel1.Mode.text = "Custom";

                Wavegen1.Channel1.Custom.Type.text =
                    "BCI_Waveform";

                Wavegen1.Channel1.Custom.Frequency.value =
                    frequency_Hz;

                Wavegen1.Channel1.Custom.Amplitude.value =
                    ad3Amplitude_V;

                Wavegen1.Channel1.Custom.Offset.value =
                    0.0;

                Wavegen1.Channel1.enable = true;

                print("");
                print("Channel 1 mode: Custom");
                print("Frequency: " + frequency_Hz + " Hz");
                print("Amplitude: " + ad3Amplitude_V + " V");
                print("Offset: 0 V");


                // --------------------------------------------
                // 10. START OUTPUT
                // --------------------------------------------

                print("");
                print("----------------------------------------");
                print("STEP 9: Starting WaveGen");
                print("----------------------------------------");

                Wavegen1.run();

                print("");
                print("WaveGen started.");


                // --------------------------------------------
                // 11. EXPECTED OUTPUT
                // --------------------------------------------

                var positiveOutput_V =
                    (maxVal / maxAbsolute) * ad3Amplitude_V;

                var negativeOutput_V =
                    (minVal / maxAbsolute) * ad3Amplitude_V;

                print("");
                print("----------------------------------------");
                print("EXPECTED OUTPUT");
                print("----------------------------------------");

                print("");
                print("AD3 positive peak: " +
                      positiveOutput_V + " V");

                print("AD3 negative peak: " +
                      negativeOutput_V + " V");

                print("");
                print("If using a 10,000:1 attenuator:");

                print("Positive peak: " +
                      (positiveOutput_V / 10000.0 * 1000000.0) +
                      " uV");

                print("Negative peak: " +
                      (negativeOutput_V / 10000.0 * 1000000.0) +
                      " uV");


                print("");
                print("========================================");
                print("BCI WAVEFORM REPLAY RUNNING");
                print("========================================");

            }
        }
    }
}